---
title: "Data for Julia on Nutritional Analysis"
author: "Juliano Palacios-Abrantes"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, results='hide', message=FALSE, echo = F}

library(MyFunctions)

packages <- c(
  "readxl", # Read dataframe
  "tidyverse", # for all data wrangling and ggplot
  "janitor", # for data cleaning
  "sf", #Spatial analysis 
  "sp", #Spatial analysis 
  "rnaturalearth", # For maps
  "doParallel",
  "foreach",
  # For netcdf files
  "ncdf4",
  "metR",
  "data.table"
)

my_lib(packages)

# Fix new updates of sf package
sf::sf_use_s2(use_s2 = FALSE)
```

# Functions

```{r main_fx, eval = F, echo = F}

# taxon = 600035

mainfx <- function(taxon){
  print(taxon)
  
  to_read <- paste0(taxon,"Catch.RData")
  
  for(m in 1:6){
    
    file_to_read <- paste0(scenarios[m],"/",to_read)
    
    if(file.exists(file_to_read)){
      
      load(file_to_read)
      
      data <- as.data.frame(data) %>% 
        rowid_to_column("index")
      colnames(data) <- c("index",(seq(1851,2100,1)))
      
      early_data <- data %>% 
        gather("year","value",`1951`:`2100`) %>% 
        select(year,value,index) %>% 
        mutate(
          period = case_when(
            year > 1995 & year < 2015 ~ "present_1995_2014",
            year > 2020 & year < 2039 ~ "mid_2020_2039",
            TRUE ~ NA_character_
          )
        ) %>% 
        filter(!is.na(period)) %>% 
        left_join(regional_grid,
                  by = "index",
                  relationship = "many-to-many") %>%
        filter(!is.na(eez_id)) %>%
        group_by(eez_name,year,period) %>% 
        # Sum total catch per eez per year
        summarise(eez_catch = sum(value, na.rm = T),.groups = "drop") %>% 
        group_by(eez_name,period) %>% 
        # Average yearly data
        summarise(mcp = mean(eez_catch,na.rm = T),.groups = "drop") %>% 
        mutate(
          taxon_key = taxon,
          esm = str_sub(file_to_read,46,49),
          ssp = ifelse(str_sub(file_to_read,50,51) == 26,"ssp126","ssp585")
        )
      
      
      # Join data for all three models
      if(m == 1){
        partial_output <- early_data
      }else{
        partial_output <- bind_rows(partial_output,early_data)
      }
      
    }else{
      partial_output
      print(file_to_read)
    }
  }
  
  print(paste(unique(partial_output$esm)))
  
  # Average ESMs +- SD
  final_output <- partial_output %>% 
    spread(period,mcp) %>% 
    mutate(
      per_change = my_chng(present_1995_2014,mid_2020_2039,100)
    ) %>% 
    filter(!is.na(per_change)) %>% 
    group_by(taxon_key,eez_name,ssp) %>% 
    summarise(mean_mcp_delta_2030 = mean(per_change, na.rm =T),
              sd_mcp_delta_2030 = sd(per_change, na.rm =T),
              .groups = "drop")
  
  
  # Save delta data for trade
  trade_name <- paste0("percentage_change_",taxon,".csv")
    write_csv(final_output,
            my_path("R","trade_results/delta_mcp/",trade_name))
  
  # Save agg data for nutrition 
  nut_name <- paste0(taxon,"_mcp.csv")
  write_csv(partial_output,
            my_path("R","mcp_nutrition",nut_name))
  
  message("Finishing processing: ", taxon)
} # Close function

```

# Data

```{r}


# eez grid ID
regional_grid <- my_data("sau_index")

# Hotspots data
hotspot_data <- my_path("D", name= "hotspots_data.csv", read = T)

# species list
# dbem_spp <- list.files(my_path("R","trade_results/delta_mcp"))

dbem_spp <- list.files("/Volumes/Enterprise/Data/dbem/dbem_update/c6gfdl26F1UP", pattern = "Catch.RData")
dbem_spp <- str_sub(dbem_spp,1,6)

ran_spp <- list.files(my_path("R","trade_results/delta_mcp"))

ran_spp <- str_sub(ran_spp,19,24)

# dbem_spp <- dbem_spp %>% 
  # filter(!taxon_key %in% ran_spp)

# Filter out species allready ran
dbem_spp <- dbem_spp[!dbem_spp %in% ran_spp]

regional_grid <-
  my_data("sau_index") %>% 
  filter(eez_name %in% hotspot_data$eez_name)

# List esm folders
scenarios <- list.files("/Volumes/Enterprise/Data/dbem/dbem_update/",full.names = T )


```

# Run protocol

```{r}
# for(i in 2:4){
# mainfx(taxon = dbem_spp[i])
# }
# spp_ran <- list.files(my_path("D",))
# detectCores()
mclapply(dbem_spp,mainfx,mc.cores = 6)

# lapply(dbem_spp$taxon_key, mainfx)


```

## Test runs

```{r}

delta_data <-
  my_path("R","trade_results/delta_mcp",fn = T, list_files = "paths")

# Check files are not corrupted
check_fx <- function(path){
  test <- try(read_csv(path,show_col_types = FALSE),silent = T)
  if(inherits(test, "try-error")){
    print(paste("Error in file:",path))
    stop()
  }else{
    print(paste("File ok:",path))
  }
}

lapply(delta_data,check_fx)

read_csv(delta_data[1],show_col_types = FALSE) %>% names()
```


# Figures 

```{r}

results_path <-
  my_path("R","mcp_nutrition",list_files = "paths")

mcp_nut_df <- bind_rows(
  lapply(results_path, fread)
) %>% 
  left_join(my_data("dbem_species")) %>% 
  select(taxon_key,taxon_name,common_name,name = eez_name,period:sd_mcp)

sau_sf <- my_sf("SAU")

```

```{r}

map_df <- mcp_nut_df %>% 
  # group_by(name,period,ssp) %>% 
  # summarise(
  #   sum_mcp = sum(mean_mcp,na.rm = T)
  # ) %>% 
  filter(
    name == "Ecuador",
    ssp == "ssp585") %>% 
  select(-sd_mcp,-name) %>% 
  spread(period,mean_mcp) %>% 
  mutate(
    per_change = my_chng(present_1995_2014,mid_2020_2039,limit = 50)
  )

map_fig <- sau_sf %>% 
  left_join(map_df) %>% 
  filter(!is.na(per_change))

map <- ggplot(map_fig) +
  my_land_map(fill = "grey70", colo = "grey70") +
  geom_sf(
    aes(
      fill = per_change
    )
  ) +
  facet_wrap(~ssp) +
  scale_fill_gradient2("Change in MCP (%)",
                       limits = c(-50,50)
  ) +
  my_ggtheme_m(leg_width = 2)

ggsave(
  "map.png",
  map,
  width = 10,
  height = 4
)

```

