---
title: "Untitled"
author: "Juliano Palacios-Abrantes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, results='hide', message=FALSE, echo = F}
library(MyFunctions)

packages <- c(
  "readxl", # Read dataframe
  "tidyverse", # for all data wrangling and ggplot
  "janitor", # for data cleaning
  "sf", #Spatial analysis 
  "sp", #Spatial analysis 
  "rnaturalearth", # For maps
  "doParallel",
  "foreach",
  # For netcdf files
  "ncdf4",
  "metR"
)

my_lib(packages)

# Fix new updates of sf package
sf::sf_use_s2(use_s2 = FALSE)
```

# Map option

```{r get_data, eval = T}

# Future Oceans data
future_data <- my_path("R",name = "aggregated_data_all_spp.csv", read = T) 


# Sau map
sau_sf <- my_sf("SAU")


```



# Gulf of Guinea

Cameroon, Congo, DRC, Equatorial Guinea, Gabon, Nigeria, Sao Tome & Principe


```{r g_guinea_data, eval = T, echo = T}

# Oceans future data
g_guinea <- future_data %>% 
  filter(
    eez_name %in% c("Cameroon","Congo (ex-Zaire)","Congo, R. of","Equatorial Guinea","Gabon","Nigeria","Sao Tome & Principe")
  )

# SAU shapefile data
g_guinea_sf <- sau_sf %>% 
  filter(
    name %in% c("Cameroon","Congo (ex-Zaire)","Congo, R. of","Equatorial Guinea","Gabon","Nigeria","Sao Tome & Principe")
  )


```


## Line plot

```{r}

g_guinea %>% 
  ggplot() +
  # geom_line(
  #   aes(
  #     x = as.numeric(year),
  #     y = mean_per_change,
  #     color = eez_name
  #   )
  # ) +
  geom_line(data = g_guinea,
            aes(
              x = as.numeric(year),
              y = per_change_rm,
              # group = eez_name,
              color = eez_name
            )
            # color = "black"
  ) +
  geom_ribbon(data = g_guinea,
              aes(
                x = as.numeric(year),
                ymax = per_change_rm+sd_per_change,
                ymin = per_change_rm-sd_per_change,
                fill = eez_name
              ),
              alpha = 0.3
  )  +
  scale_color_viridis_d("Gulf of Guinea EEZ") +
  scale_fill_viridis_d("Gulf of Guinea EEZ") +
  scale_y_continuous(limits =c(-100,50),
                     breaks = c(-100,-50,0,50)
  ) +
  my_ggtheme_p(ax_tx_s = 9,ax_tl_s = 10,leg_tl_s = 10,leg_tx_s = 10,leg_pos = "bottom",facet_tx_s = "0") +
  labs(
    x= "Year",
    y = "% Change Relative to Historical Value\n(All species aggregated)"
  ) +
  facet_wrap(~ssp)

ggsave(plot = last_plot(),
       filename = my_path("R", "hotspot_report", name = "gulf_guinea_lines.png"),
       width = 8,
       height = 4
)

```


## Map figure

```{r}

g_guinea_2050 <- g_guinea %>% 
  filter(year >= 2040 & year <= 2059) %>% 
  group_by(name = eez_name, ssp) %>% 
  summarise(change = mean(mean_per_change))


g_guinea_map <- 
  g_guinea_sf %>% 
  left_join(g_guinea_2050,
            by = "name") %>% 
  ggplot() +
  my_land_map(fill = "grey80") +
  geom_sf(aes(fill = change)) +
  geom_sf_label(aes(label = name, fill = change), size = 2, color = "white") +
  # scale_color_viridis_b("% Change Relative to Historical Value\n(All species aggregated)") +
  scale_fill_viridis_b("% Change by 2050 Relative to Historical Value", limits = c(-80,-20),breaks = seq(-80,-20,10),
                           guide = guide_colorbar(title.position = "right", title.hjust = 0.5, barwidth = 1, barheight = 15)
                       ) +
  my_ggtheme_p(ax_tx_s = 9,ax_tl_s = 10,leg_tl_s = 10,leg_tx_s = 10,leg_pos = "right",facet_tx_s = "10") +
  theme(legend.title = element_text(angle = 270, vjust = 0.5, hjust = 0.5))+
  labs(
    x= "Longitude",
    y = "Latitude"
  ) +
  coord_sf(xlim = c(0,14),
           ylim = c(-7,7)) +
  facet_wrap(~ssp,
             labeller = labeller(ssp = c("126" = "SSP1-2.6",
                                         "585" = "SSP5-8.5"))
             )


ggsave(plot = g_guinea_map,
       filename = my_path("R", "hotspot_report", name = "gulf_guinea_map.png"),
       width = 8,
       height = 4
)


```

